---
- name: Setup VM
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    acpi: "{{ item.acpi | default(omit) }}"
    agent: "{{ item.agent | default(omit) }}"
    autostart: "{{ item.autostart | default(omit) }}"
    balloon: "{{ item.balloon | default(omit) }}"
    bios: "{{ item.bios | default(omit) }}"
    boot: "{{ item.boot | default(omit) }}"
    bootdisk: "{{ item.bootdisk | default(omit) }}"
    cicustom: "{{ item.cicustom | default(omit) }}"
    cipassword: "{{ item.cipassword | default(omit) }}"
    citype: "{{ item.citype | default(omit) }}"
    ciuser: "{{ item.ciuser | default(omit) }}"
    clone: "{{ item.clone | default(omit) }}"
    cores: "{{ item.cores }}"
    cpu: "{{ item.cpu | default(omit) }}"
    cpulimit: "{{ item.cpulimit | default(omit) }}"
    cpuunits: "{{ item.cpuunits | default(omit) }}"
    delete: "{{ item.delete | default(omit) }}"
    description: "{{ item.description | default(omit)  }}"
    digest: "{{ item.digest | default(omit)  }}"
    efidisk0: "{{ item.efidisk0 | default(omit)  }}"
    format: "{{ item.format | default(omit) }}"
    freeze: "{{ item.freeze | default(omit) }}"
    full: "{{ item.full | default(omit) }}"
    hostpci: "{{ item.hostpci | default(omit) }}"
    hotplug: "{{ item.hotplug | default(omit) }}"
    hugepages: "{{ item.hugepages | default(omit) }}"
    ide: "{{ item.ide | default(omit) }}"
    ipconfig: "{{ item.ipconfig | default(omit) }}"
    keyboard: "{{ item.keyboard | default(omit) }}"
    kvm: "{{ item.kvm | default(omit) }}"
    localtime: "{{ item.localtime | default(omit) }}"
    lock: "{{ item.lock | default(omit) }}"
    machine: "{{ item.machine | default(omit) }}"
    memory: "{{ item.memory }}"
    name: "{{ item.name }}"
    nameservers: "{{ item.nameservers | default(omit) }}"
    net: "{{ item.net }}"
    newid: "{{ item.newid | default(omit) }}"
    node: "{{ item.node }}"
    numa: "{{ item.numa | default(omit) }}"
    numa_enabled: "{{ item.numa_enabled | default(omit) }}"
    onboot: "{{ item.onboot | default(omit) }}"
    pool: "{{ item.pool | default(omit) }}"
    protection: "{{ item.protection | default(omit) }}"
    sata: "{{ item.sata | default(omit) }}"
    scsi: "{{ item.scsi | default(omit) }}"
    scsihw: "{{ item.scsihw | default(omit) }}"
    searchdomains: "{{ item.searchdomains | default(omit) }}"
    serial: "{{ item.serial | default(omit) }}"
    shares: "{{ item.shares | default(omit) }}"
    sockets: "{{ item.sockets | default(omit) }}"
    sshkeys: "{{ item.sshkeys | default(omit) }}"
    startup: "{{ item.startup | default(omit) }}"
    storage: "{{ item.storage | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    target: "{{ item.target | default(omit) }}"
    tdf: "{{ item.tdf | default(omit) }}"
    update: "
      {% if 'update' in item %}
      {{ item['update'] }}
      {% else %}
      {{ proxmox_kvm_update }}
      {% endif %}"
    validate_certs: "{{ proxmox_api_validate_certs }}"
    vcpus: "{{ item.vcpus | default(omit) }}"
    virtio: "{{ item.virtio | default(omit) }}"
    vmid: "{{ item.vmid }}"
  when: not ansible_check_mode
  retries: 10
  delay: 3
  register: vm
  until: vm.vmid is defined
  loop: "{{ proxmox_vm }}"

- name: Manage VM state
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    name: "{{ item.name }}"
    node: "{{ item.node }}"
    state: "{{ item.state | default('started') }}"
    validate_certs: "{{ proxmox_api_validate_certs }}"
  when: not ansible_check_mode
  retries: 10
  delay: 3
  register: vm
  until: vm.vmid is defined
  loop: "{{ proxmox_vm }}"
