---
- name: Setup LXC Containers
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ item.api_token_id | default(proxmox_api_token_id) }}"
    api_token_secret: "{{ item.api_token_secret | default(proxmox_api_token_secret) }}"
    api_user: "{{ item.api_user | default(proxmox_api_user) }}"
    clone: "{{ item.clone | default(omit) }}"
    clone_type: "{{ item.clone_type | default(omit) }}"
    cores: "{{ item.cores | default(1) }}"
    cpus: "{{ item.cpus | default(1) }}"
    cpuunits: "{{ item.cpuunits | default(1000) }}"
    description: "{{ item.description | default(omit) }}"
    disk: "{{ item.disk | default(omit) }}"
    disk_volume: "{{ item.disk_volume | default(omit) }}"
    features: "{{ item.features | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    hookscript: "{{ item.hookscript | default(omit) }}"
    hostname: "{{ item.hostname }}"
    ip_address: "{{ item.ip_address | default(omit) }}"
    memory: "{{ item.memory | default(512) }}"
    mount_volumes: "{{ item.mount_volumes | default(omit) }}"
    mounts: "{{ item.mounts | default(omit) }}"
    nameserver: "{{ item.nameserver | default(omit) }}"
    netif: "{{ item.netif | default(omit) }}"
    node: "{{ item.node | default(omit) }}"
    onboot: "{{ item.onboot | default(False) }}"
    ostemplate: "{{ item.ostemplate | default(omit) }}"
    ostype: "{{ item.ostype | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    pool: "{{ item.pool | default(omit) }}"
    pubkey: "{{ item.pubkey | default(proxmox_pubkey) | default(omit) }}"
    purge: "{{ item.purge | default(omit) }}"
    searchdomain: "{{ item.searchdomain | default(omit) }}"
    startup: "{{ item.startup | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    storage: "{{ item.storage | default(omit) }}"
    swap: "{{ item.swap | default(0) }}"
    tags: "{{ item.tags | default(omit) }}"
    timeout: "{{ item.timeout | default(120) }}"
    timezone: "{{ item.timeout | default(omit) }}"
    unprivileged: "{{ item.unprivileged | default(omit) }}"
    update: "{{ ('update' in item) | ternary(item['update']|bool, omit) }}"
    validate_certs: "{{ item.validate_certs | default(proxmox_api_validate_certs) | bool }}"
    vmid: "{{ item.vmid | default(omit) }}"
  loop: "{{ proxmox_container }}"
  throttle: 1

- name: Verify that LXC container exists
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ item.api_token_id | default(proxmox_api_token_id) }}"
    api_token_secret: "{{ item.api_token_secret | default(proxmox_api_token_secret) }}"
    api_user: "{{ item.api_user | default(proxmox_api_user) }}"
    hostname: "{{ item.hostname }}"
    node: "{{ item.node }}"
    state: present
    validate_certs: "{{ item.validate_certs | default(proxmox_api_validate_certs) | bool }}"
    vmid: "{{ item.vmid }}"
  loop: "{{ proxmox_container }}"
  when: not ansible_check_mode
  register: __lxc_present
  until: "'is already' in __lxc_present.msg"
  retries: 10
  delay: 1

- name: Manage Containers state
  community.general.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ item.node }}"
    hostname: "{{ item.hostname }}"
    vmid: "{{ item.vmid }}"
    state: "{{ item.state | default('started') }}"
  loop: "{{ proxmox_container }}"
